### ISSUE TITLE
Lab 1: Validator passes if one man is chosen by all women

### ISSUE THREAD

**Issue by davidsoederberg** [LarsAstrom/EDAF05-labs-public#12]
If you have a bug in your code that makes all women point to the same man the tests will pass. For example: `(1,1), (2,1), (3,1), (4,1)` It will pass all tests because `output_validator.py` only checks preferences order using less than, which means it does not check if they point to the same man.

A simple code to recreate the problem would be to just print out '1' N times: 
```
for(int i = 0; i<N; i++){
     System.out.println(1);
 }
```

Maybe I missed something that breaks if we add equal signs to the comparings on row 29 and 32, but it seems to work for me when I edit the validator.

**Comment by LarsAstrom** [comment]
Now this should be fixed. Thank you for the issue!
